### ISSUE TITLE
The ascii of text.neovim.sharp looks weird on my device

### ISSUE THREAD

**Issue by benkwyan** [MaximilianLloyd/ascii.nvim#12]
![Image](https://github.com/user-attachments/assets/9105fea3-c8e6-45e5-8003-8b6366d33d4f)

The ascii art looks kinda off but I cannot figure out the reason. Is it some issue related to terminal font?

**Comment by fabridamicelli** [comment]
Same here 

![Image](https://github.com/user-attachments/assets/b693e6b7-3028-462a-b55b-d638bc255ac6)

**Comment by MaximilianLloyd** [comment]
Hmm that's strange, could you share what font you are using so i can debug it?

**Comment by fabridamicelli** [comment]
> Hmm that's strange, could you share what font you are using so i can debug it?
here's my alacritty.toml section
```toml
[font]
normal = { family = "CaskaydiaMono Nerd Font", style = "Regular" }
bold = { family = "CaskaydiaMono Nerd Font", style = "Bold" }
italic = { family = "CaskaydiaMono Nerd Font", style = "Italic" }

```
